### PR TITLE
Add commands to control extension with keyboard

### PR DESCRIPTION
**Pull request by tarnas14**
I really like how simple this extension is (it does one job and does it well)

I am not a fan of using pointers, so I added hooks for keyboard shortcuts :)

### CODE REVIEW

**Comment by maxkrieger** [comment]
Hey Mateusz, thanks so much for the PR! Admittedly I don't maintain this as much as I should, even though I use it often.

I thought <kbd>cmd-D</kbd> and <kbd>ctrl-D</kbd> were reserved for bookmarking? It's possible I'm reading the code wrong. What about <kbd>ctrl/cmd-shift-x</kbd>?

**Comment by tarnas14** [comment]
don't worry, it's good enough as it is! :)

you are right about `ctrl-D`, I had it disabled and didn't see the clash (funnily enough `ctrl-shift-x` clashes with another one of mine), changed to `ctrl+sfhit+x`

**Comment by maxkrieger** [comment]
Done and published! I made the default control toggle instead of enable.
Thanks!

**Comment by tarnas14** [comment]
makes sense, but for my purposes I want to make deactivating the addon that little bit harder ^^ I'll add picture state change in some free time in the future

**Pull request merged**
